services:

  personal-trainer:
    build: server-a
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/shared
    network_mode: "host"
    environment:
      - "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"

  gateway-agent:
    build: gateway-agent
    command:
      - /app/listen.sh
    volumes:
      - ./shared:/shared
    network_mode: "host"
    environment:
      - "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"



